<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="/assets/css/style.css?v=8332a557061e2b4053e543da2b02656a4de57cdb">
    <link rel="stylesheet" type="text/css" href="/assets/css/print.css" media="print">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<!-- Begin Jekyll SEO tag v2.6.1 -->
<title>简历 | Wang-xd1899.github.io</title>
<meta name="generator" content="Jekyll v3.9.0" />
<meta property="og:title" content="简历" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Wang.Xidodong personal website" />
<meta property="og:description" content="Wang.Xidodong personal website" />
<link rel="canonical" href="https://wang-xd1899.github.io/" />
<meta property="og:url" content="https://wang-xd1899.github.io/" />
<meta property="og:site_name" content="Wang-xd1899.github.io" />
<script type="application/ld+json">
{"@type":"WebSite","headline":"简历","url":"https://wang-xd1899.github.io/","description":"Wang.Xidodong personal website","name":"Wang-xd1899.github.io","@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->

  </head>

  <body>
    <div id="container">
      <div class="inner">

        <header>
          <h1>简历</h1>
          <h2>Wang.Xidodong personal website</h2>
        </header>
        <section id="downloads" class="clearfix">
          
	
        </section>
        <hr>
        <section id="main_content">
          <!--<h2 id="简历">简历</h2>-->
<h3 id="个人信息">个人信息</h3>
<p>姓名：王晓东<br />
性别：男<br />
学校：<a href="https://www.bistu.edu.cn">北京信息科技大学</a></p>
<h3 id="教育经历">教育经历</h3>
<p>2017年9月-2021年7月：<br />
北京信息科技大学 数据科学与大数据技术专业 本科生<br /></p>
<h3 id="所获荣誉">所获荣誉</h3>
<p>2017-2018学年度国家奖学金<br />
2018-2019学年度国家励志奖学金<br />
2018-2019学年北京信息科技大学校长奖学金（全校10名，不分本硕）</p>
<h3 id="论文出版">论文出版</h3>
<p><strong>Wang, Xiaodong</strong> , et al. Background Cleaning and Direction Weight in Salient Object Detection. Pattern Recognition and Computer Vision, Third Chinese Conference, PRCV 2020. (录用率：39.8%，<a href="http://www.prcv.cn">国内视觉顶会</a>)<br />
<strong>Wang, Xiaodong</strong> , Z. Wang , and X. Huang . “Salient Object Detection via Depth and Contrast Networks.” ICMSSP 2020: 2020 5th International Conference on Multimedia Systems and Signal Processing 2020. (EI)<br />
Jia M, <strong>Wang X</strong>, Xu Y, et al. Testing Machine Learning Classifiers based on Compositional Metamorphic Relations[J]. International journal of performability engineering, 2020, 16(1). (EI)<br />
<img src="https://github.com/Sheldonwg/Sheldonwg.github.io/blob/master/AMI.jpg" width="150" height="150" alt="图片加载失败" /></p>

        </section>

        <footer>
        
          This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.
        </footer>

      </div>
    </div>

    
  </body>
</html>
